name: CI-CD Docker Pipeline
on:
  push:
    branches:
      - main
env:
  IMAGE_NAME: ci-html
  IMAGE_TAG: 1.0.1
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USER" --password-stdin
      - name: Build Docker image
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          docker build -t $DOCKER_USER/$IMAGE_NAME:$IMAGE_TAG .
      - name: Push Docker image
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          docker push $DOCKER_USER/$IMAGE_NAME:$IMAGE_TAG
  scan-trivy:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/ci-html:1.0.1
          format: table
          severity: CRITICAL,HIGH
          exit-code: 0
          vuln-type: os,library
          ignore-unfixed: true
  deploy:
    needs: [ci, scan-trivy]
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest image
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          docker pull $DOCKER_USER/$IMAGE_NAME:$IMAGE_TAG
      - name: Stop existing container
        run: docker stop ci-app || true
      - name: Remove old container
        run: docker rm ci-app || true
      - name: Run new container
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          docker run -d -p 80:80 --name ci-app $DOCKER_USER/$IMAGE_NAME:$IMAGE_TAG
